name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  UnitTest:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Test 
      run: pnpm run test
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - run: pnpm install
    - run: pnpm test
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}